function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const crossFilters = (...filter) => ({ filter, highlight: [], none: [] });

export const COMERCIAL_DEFINITION = deepFreeze({
  id: "comercial",
  title: "COMERCIAL",
  sourceEntityIds: [
    "apontamentos-comerciais",
    "clientes",
    "filiais",
    "homologacoes-de-fornecedor",
    "imoveis",
    "compras",
    "receitas",
    "lancamentos",
  ],
  filters: [
    { id: "filial", title: "FILIAL", sourceEntityId: "filiais", field: "FILIAIS.FILIAL", aliases: ["FILIAL"] },
    { id: "mes", title: "DATA", sourceEntityId: "receitas", field: "dCalendário.Date.Mês", aliases: ["DATAPGTOEFETUADO"], granularity: "month" },
    { id: "ano", title: "ANO", sourceEntityId: "receitas", field: "dCalendário.Date.Ano", aliases: ["DATAPGTOEFETUADO"], granularity: "year" },
    { id: "forma-pagamento", title: "FORMA PGTO", sourceEntityId: "lancamentos", field: "LANÇAMENTOS.CONTA", aliases: ["CONTA"] },
    { id: "imovel", title: "IMÓVEL", sourceEntityId: "apontamentos-comerciais", field: "APONTAMENTOSCOMERCIAIS.IMOVEL", aliases: ["IMOVEL"] },
  ],
  kpis: [
    {
      id: "total-vendas",
      title: "TOTAL VENDAS",
      sourceEntityId: "receitas",
      operation: "sum",
      aliases: ["VALORTOTAL"],
      valueAliases: ["VALORTOTAL"],
      measure: "Sum(LANÇAMENTORECEITA.VALORTOTAL)",
      format: "currency",
    },
    {
      id: "total-receitas",
      title: "TOTAL RECEITAS",
      sourceEntityId: "receitas",
      operation: "sum",
      aliases: ["VALORPAGO"],
      valueAliases: ["VALORPAGO"],
      measure: "Sum(LANÇAMENTORECEITA.VALORPAGO)",
      format: "currency",
    },
  ],
  charts: [
    {
      id: "receita-por-periodo",
      title: "lineChart",
      type: "lineChart",
      sourceEntityId: "receitas",
      dimensions: [
        "LANÇAMENTORECEITA.DATAPGTOEFETUADO.Variation.Hierarquia de datas.Ano",
        "LANÇAMENTORECEITA.DATAPGTOEFETUADO.Variation.Hierarquia de datas.Mês",
        "LANÇAMENTORECEITA.DATAPGTOEFETUADO.Variation.Hierarquia de datas.Dia",
      ],
      measures: ["Sum(LANÇAMENTORECEITA.VALORTOTAL)"],
      dimensionAliases: ["DATAPGTOEFETUADO"],
      operation: "sum",
      valueAliases: ["VALORTOTAL"],
      interaction: "cross-filter",
      crossFilters: crossFilters("receita-por-cliente", "vendas-por-corretor", "receita-por-filial", "documentos-por-filial"),
    },
    {
      id: "receita-por-cliente",
      title: "RECEITA/CLIENTE",
      type: "barChart",
      sourceEntityId: "receitas",
      dimensions: ["CADASTRO CLIENTE.NOME"],
      measures: ["Sum(LANÇAMENTORECEITA.VALOR_NAO_PAGO)", "Sum(LANÇAMENTORECEITA.VALORPAGO)"],
      dimensionAliases: ["FORNECEDOR", "NOME"],
      operation: "sum",
      valueAliases: ["VALOR_NAO_PAGO", "VALORPAGO"],
      interaction: "cross-filter",
      crossFilters: crossFilters("vendas-por-corretor", "imoveis-por-filial", "documentos-por-filial", "receita-por-filial"),
    },
    {
      id: "vendas-por-corretor",
      title: "VENDAS/CORRETOR",
      type: "barChart",
      sourceEntityId: "compras",
      dimensions: ["LANCAMENTOCOMPRAS.CORRETOR"],
      measures: ["Sum(LANÇAMENTORECEITA.VALORPAGO)", "Sum(LANÇAMENTORECEITA.VALOR_NAO_PAGO)"],
      dimensionAliases: ["CORRETOR"],
      operation: "sum",
      valueAliases: ["VALORPAGO", "VALOR_NAO_PAGO"],
      interaction: "cross-filter",
      crossFilters: crossFilters("receita-por-cliente", "imoveis-por-filial", "documentos-por-filial", "receita-por-filial"),
    },
    {
      id: "documentos-por-filial",
      title: "DOCUMENTOS/FILIAL",
      type: "barChart",
      sourceEntityId: "homologacoes-de-fornecedor",
      dimensions: ["HOMOLOGACAOCOMERCIAL.CLIENTE", "HOMOLOGACAOCOMERCIAL.FILIAL", "HOMOLOGACAOCOMERCIAL.TIPODOCUMENTO"],
      measures: ["CountNonNull(HOMOLOGACAOCOMERCIAL.CLIENTE)"],
      dimensionAliases: ["FILIAL", "TIPODOCUMENTO"],
      operation: "count",
      valueAliases: ["CLIENTE"],
      interaction: "cross-filter",
      crossFilters: crossFilters("receita-por-cliente", "vendas-por-corretor", "imoveis-por-filial", "receita-por-filial"),
    },
    {
      id: "imoveis-por-filial",
      title: "IMÓVEIS/FILIAL",
      type: "hundredPercentStackedColumnChart",
      sourceEntityId: "imoveis",
      dimensions: ["FILIAIS.FILIAL", "IMOVEL CADASTRADO.IMOVEL", "IMOVEL CADASTRADO.STATUS"],
      measures: ["CountNonNull(IMOVEL CADASTRADO.IMOVEL)"],
      dimensionAliases: ["FILIAL", "STATUS"],
      operation: "count",
      valueAliases: ["IMOVEL"],
      interaction: "cross-filter",
      crossFilters: crossFilters("vendas-por-corretor", "receita-por-cliente", "documentos-por-filial", "receita-por-filial"),
    },
    {
      id: "receita-por-filial",
      title: "RECEITA/FILIAL",
      type: "columnChart",
      sourceEntityId: "receitas",
      dimensions: [
        "FILIAIS.FILIAL",
        "dCalendário.Date.Variation.Hierarquia de datas.Ano",
        "dCalendário.Date.Variation.Hierarquia de datas.Trimestre",
        "dCalendário.Date.Variation.Hierarquia de datas.Mês",
        "dCalendário.Date.Variation.Hierarquia de datas.Dia",
      ],
      measures: ["Sum(LANÇAMENTORECEITA.VALORPAGO)", "Sum(LANÇAMENTORECEITA.VALOR_NAO_PAGO)"],
      dimensionAliases: ["FILIAL", "DATAPGTOEFETUADO"],
      operation: "sum",
      valueAliases: ["VALORPAGO", "VALOR_NAO_PAGO"],
      interaction: "cross-filter",
      crossFilters: crossFilters("total-vendas", "vendas-por-corretor", "receita-por-cliente", "imoveis-por-filial", "documentos-por-filial"),
    },
    {
      id: "documentos-por-imovel",
      title: "DOCUMENTOS/IMÓVEL",
      type: "barChart",
      sourceEntityId: "homologacoes-de-fornecedor",
      dimensions: ["HOMOLOGACAOCOMERCIAL.CLIENTE", "HOMOLOGACAOCOMERCIAL.IMOVEL", "HOMOLOGACAOCOMERCIAL.TIPODOCUMENTO"],
      measures: ["CountNonNull(HOMOLOGACAOCOMERCIAL.CLIENTE)"],
      dimensionAliases: ["IMOVEL", "TIPODOCUMENTO"],
      operation: "count",
      valueAliases: ["CLIENTE"],
      interaction: "cross-filter",
      crossFilters: crossFilters(),
    },
    {
      id: "cronograma-comercial",
      title: "Gantt1448688115699",
      type: "gantt",
      sourceEntityId: "apontamentos-comerciais",
      dimensions: ["APONTAMENTOSCOMERCIAIS.TIPOMARCO"],
      measures: ["Min(APONTAMENTOSCOMERCIAIS.DATA EM ATENDIMENTO)", "Sum(APONTAMENTOSCOMERCIAIS.%)"],
      dimensionAliases: ["TIPOMARCO"],
      startAliases: ["DATAINICIO"],
      endAliases: ["DATA EM ATENDIMENTO"],
      durationAliases: ["DIAS"],
      progressAliases: ["%"],
      interaction: "cross-filter",
      crossFilters: crossFilters(),
    },
  ],
  table: {
    id: "documentos-receita",
    title: "DOCUMENTOS",
    type: "tableEx",
    sourceEntityId: "receitas",
    source: "LANÇAMENTORECEITA",
    columns: [
      { id: "data", title: "DATA", field: "LANÇAMENTORECEITA.DATA", aliases: ["DATA"], type: "date" },
      { id: "data-pagamento", title: "DATAPGTOEFETUADO", field: "LANÇAMENTORECEITA.DATAPGTOEFETUADO", aliases: ["DATAPGTOEFETUADO"], type: "date" },
      { id: "descricao", title: "DESCRIÇÃO", field: "LANÇAMENTORECEITA.DESCRIÇÃO", aliases: ["DESCRIÇÃO", "DESCRICAO"] },
      { id: "filial", title: "FILIAL", field: "LANÇAMENTORECEITA.FILIAL", aliases: ["FILIAL"] },
      { id: "forma-pagamento", title: "FORMAPGTO", field: "LANÇAMENTORECEITA.FORMAPGTO", aliases: ["FORMAPGTO"] },
      { id: "fornecedor", title: "FORNECEDOR", field: "LANÇAMENTORECEITA.FORNECEDOR", aliases: ["FORNECEDOR"] },
      { id: "valor-total", title: "VALORTOTAL", field: "LANÇAMENTORECEITA.VALORTOTAL", aliases: ["VALORTOTAL"], type: "currency" },
    ],
    crossFilters: crossFilters(),
  },
});

export default COMERCIAL_DEFINITION;
