function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const OBRA_VISUAL_IDS = [
  "cronograma-fisico", "custo-fornecedor", "percentual-produto", "profissoes-dia",
  "presencas-profissional", "profissionais-etapa", "atividades-executadas",
  "distribuicao-forma-pagamento", "apontamentos-funcionarios", "tipo-despesa", "tipo-despesa-etapa",
];
const crossFiltersFor = (id, none = []) => ({
  filter: OBRA_VISUAL_IDS.filter(target => target !== id && !none.includes(target)),
  highlight: [],
  none,
});

export const ETAPA_OBRA_DEFINITION = deepFreeze({
  id: "etapa-obra",
  title: "ETAPA OBRA",
  sourceEntityIds: [
    "apontamentos-de-funcionarios",
    "produtos",
    "descricoes-de-presenca",
    "filiais",
    "fornecedores",
    "lancamentos-de-obras",
    "lancamentos",
  ],
  filters: [
    {
      id: "presenca-presente",
      title: "PRESENÇA",
      sourceEntityId: "descricoes-de-presenca",
      aliases: ["PRESENCA"],
      scope: "global",
      operator: "in",
      values: ["PRESENTE"],
    },
    { id: "filial", title: "FILIAL", sourceEntityId: "filiais", aliases: ["FILIAL"] },
    { id: "etapa", title: "ETAPA", sourceEntityId: "lancamentos-de-obras", aliases: ["ETAPA"] },
    { id: "fornecedor", title: "FORNECEDOR", sourceEntityId: "fornecedores", aliases: ["FORNECEDOR"] },
    { id: "produto", title: "PRODUTO", sourceEntityId: "lancamentos", aliases: ["PRODUTO"] },
    { id: "tipo-fornecedor", title: "TIPO", sourceEntityId: "fornecedores", aliases: ["TIPO"] },
    { id: "mes", title: "DATA", sourceEntityId: "lancamentos", aliases: ["DATA PGTO EFETUADO", "Date"], granularity: "month" },
    { id: "ano", title: "ANO", sourceEntityId: "lancamentos", aliases: ["DATA PGTO EFETUADO", "Date"], granularity: "year" },
    { id: "status-obra", title: "STATUS", sourceEntityId: "lancamentos-de-obras", aliases: ["STATUS"] },
    {
      id: "filial-obra",
      title: "LANCAMENTOOBRA.FILIAL",
      aliases: ["FILIAL"],
      sourceEntityId: "lancamentos-de-obras",
      scope: "page",
      selectionMode: "inverted",
      values: [],
    },
    {
      id: "indice-obra",
      title: "LANCAMENTOOBRA.INDICE",
      aliases: ["INDICE"],
      sourceEntityId: "lancamentos-de-obras",
      scope: "page",
      mode: "advanced",
      values: [],
    },
  ],
  kpis: [],
  charts: [
    {
      id: "cronograma-fisico",
      title: "Gantt1448688115699",
      type: "timeline",
      sourceEntityId: "lancamentos-de-obras",
      dimensionAliases: ["ETAPA ORDENADA"],
      startAliases: ["DATA INICIO CORRIGIDA"],
      endAliases: ["DATA EM ATENDIMENTO"],
      durationAliases: ["DIAS"],
      progressAliases: ["PERCENTUALEFETUADO"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("cronograma-fisico"),
    },
    {
      id: "custo-fornecedor",
      title: "barChart",
      type: "bar",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS", "PENDENTE PGTO"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("custo-fornecedor"),
    },
    {
      id: "percentual-produto",
      title: "% PRODUTO",
      type: "bar",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["FAMÍLIA", "GRUPO", "PRODUTO", "SUBFAMÍLIA"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS", "PENDENTE PGTO"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("percentual-produto"),
    },
    {
      id: "profissoes-dia",
      title: "columnChart",
      type: "column",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["Date"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("profissoes-dia"),
    },
    {
      id: "presencas-profissional",
      title: "barChart",
      type: "bar",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["FORNECEDOR"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("presencas-profissional"),
    },
    {
      id: "profissionais-etapa",
      title: "barChart",
      type: "bar",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["ETAPA"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("profissionais-etapa"),
    },
    {
      id: "atividades-executadas",
      title: "barChart",
      type: "bar",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["ATIVIDADEEXECUTADA"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("atividades-executadas"),
    },
    {
      id: "distribuicao-forma-pagamento",
      title: "DISTRIBUIÇÃO POR FORMA PGTO",
      type: "column",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["Date"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("distribuicao-forma-pagamento"),
    },
    {
      id: "apontamentos-funcionarios",
      title: "barChart",
      type: "bar",
      sourceEntityId: "apontamentos-de-funcionarios",
      dimensionAliases: ["ETAPA"],
      seriesAliases: ["TIPO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("apontamentos-funcionarios"),
    },
    {
      id: "tipo-despesa",
      title: "% TIPO DESPESA",
      type: "column",
      sourceEntityId: "produtos",
      dimensionAliases: ["TIPODESPESA"],
      seriesAliases: ["FILIAL"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("tipo-despesa", [
        "cronograma-fisico", "distribuicao-forma-pagamento", "profissoes-dia",
      ]),
    },
    {
      id: "tipo-despesa-etapa",
      title: "TIPO DESPESA/ETAPA",
      type: "bar",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["TIPODESPESA", "ETAPA"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("tipo-despesa-etapa"),
    },
  ],
  table: {
    columns: [],
  },
});

export default ETAPA_OBRA_DEFINITION;
