function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

export const ETAPA_OBRA_DEFINITION = deepFreeze({
  id: "etapa-obra",
  title: "ETAPA OBRA",
  sourceEntityIds: [
    "apontamentos-de-funcionarios",
    "produtos",
    "descricoes-de-presenca",
    "filiais",
    "fornecedores",
    "lancamentos-de-obras",
    "lancamentos",
  ],
  filters: [
    {
      id: "presenca-presente",
      title: "PRESENÇA",
      aliases: ["PRESENCA"],
      scope: "global",
      operator: "in",
      values: ["PRESENTE"],
    },
    { id: "filial", title: "FILIAL", aliases: ["FILIAL"] },
    { id: "etapa", title: "ETAPA", aliases: ["ETAPA"] },
    { id: "fornecedor", title: "FORNECEDOR", aliases: ["FORNECEDOR"] },
    { id: "produto", title: "PRODUTO", aliases: ["PRODUTO"] },
    { id: "tipo-fornecedor", title: "TIPO", aliases: ["TIPO"] },
    { id: "mes", title: "DATA", aliases: ["Date"], granularity: "month" },
    { id: "ano", title: "ANO", aliases: ["Date"], granularity: "year" },
    { id: "status-obra", title: "STATUS", aliases: ["STATUS"] },
    {
      id: "filial-obra",
      title: "LANCAMENTOOBRA.FILIAL",
      aliases: ["FILIAL"],
      scope: "page",
      selectionMode: "inverted",
      values: [],
    },
    {
      id: "indice-obra",
      title: "LANCAMENTOOBRA.INDICE",
      aliases: ["INDICE"],
      scope: "page",
      mode: "advanced",
      values: [],
    },
  ],
  kpis: [],
  charts: [
    {
      id: "cronograma-fisico",
      title: "Gantt1448688115699",
      type: "timeline",
      dimensionAliases: ["ETAPA ORDENADA"],
      startAliases: ["DATA INICIO CORRIGIDA"],
      endAliases: ["DATA EM ATENDIMENTO"],
      durationAliases: ["DIAS"],
      progressAliases: ["PERCENTUALEFETUADO"],
      interaction: "cross-filter",
    },
    {
      id: "custo-fornecedor",
      title: "barChart",
      type: "bar",
      dimensionAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS", "PENDENTE PGTO"],
      interaction: "cross-filter",
    },
    {
      id: "percentual-produto",
      title: "% PRODUTO",
      type: "bar",
      dimensionAliases: ["FAMÍLIA", "GRUPO", "PRODUTO", "SUBFAMÍLIA"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS", "PENDENTE PGTO"],
      interaction: "cross-filter",
    },
    {
      id: "profissoes-dia",
      title: "columnChart",
      type: "column",
      dimensionAliases: ["Date"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "presencas-profissional",
      title: "barChart",
      type: "bar",
      dimensionAliases: ["FORNECEDOR"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "profissionais-etapa",
      title: "barChart",
      type: "bar",
      dimensionAliases: ["ETAPA"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "atividades-executadas",
      title: "barChart",
      type: "bar",
      dimensionAliases: ["ATIVIDADEEXECUTADA"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "distribuicao-forma-pagamento",
      title: "DISTRIBUIÇÃO POR FORMA PGTO",
      type: "column",
      dimensionAliases: ["Date"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "apontamentos-funcionarios",
      title: "barChart",
      type: "bar",
      dimensionAliases: ["ETAPA"],
      seriesAliases: ["TIPO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "tipo-despesa",
      title: "% TIPO DESPESA",
      type: "column",
      dimensionAliases: ["TIPODESPESA"],
      seriesAliases: ["FILIAL"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
    },
    {
      id: "tipo-despesa-etapa",
      title: "TIPO DESPESA/ETAPA",
      type: "bar",
      dimensionAliases: ["TIPODESPESA", "ETAPA"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
    },
  ],
  table: {
    columns: [],
  },
});

export default ETAPA_OBRA_DEFINITION;
