function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const crossFilters = (filter = [], none = []) => ({ filter, highlight: [], none });

export const FINANCEIRO_DEFINITION = deepFreeze({
  id: "financeiro",
  title: "FINANCEIRO",
  sourceEntityIds: ["lancamentos", "produtos", "filiais", "lancamentos-de-obras"],
  filters: [
    { id: "produto", title: "PRODUTO", sourceEntityId: "lancamentos", field: "LANÇAMENTOS.PRODUTO", aliases: ["PRODUTO"] },
    { id: "subfamilia", title: "SUBFAMÍLIA", sourceEntityId: "lancamentos", field: "LANÇAMENTOS.SUBFAMÍLIA", aliases: ["SUBFAMÍLIA"] },
    { id: "familia", title: "FAMÍLIA", sourceEntityId: "lancamentos", field: "LANÇAMENTOS.FAMÍLIA", aliases: ["FAMÍLIA"] },
    { id: "grupo", title: "GRUPO", sourceEntityId: "lancamentos", field: "LANÇAMENTOS.GRUPO", aliases: ["GRUPO"] },
    { id: "forma-pagamento", title: "FORMA PGTO", sourceEntityId: "lancamentos", field: "LANÇAMENTOS.CONTA", aliases: ["CONTA"] },
    { id: "mes", title: "DATA", sourceEntityId: "lancamentos", field: "dCalendário.Date.Mês", aliases: ["DATA PGTO EFETUADO"], granularity: "month" },
    { id: "ano", title: "ANO", sourceEntityId: "lancamentos", field: "dCalendário.Date.Ano", aliases: ["DATA PGTO EFETUADO"], granularity: "year" },
    { id: "fornecedor", title: "FORNECEDOR", sourceEntityId: "lancamentos", field: "LANÇAMENTOS.FORNECEDOR", aliases: ["FORNECEDOR"] },
    { id: "etapa", title: "ETAPA", sourceEntityId: "lancamentos-de-obras", field: "LANCAMENTOOBRA.ETAPA", aliases: ["ETAPA"] },
    { id: "tipo-despesa", title: "TIPO DESPESA", sourceEntityId: "produtos", field: "CADASTROPRODUTO.TIPODESPESA", aliases: ["TIPODESPESA", "TIPO DESPESA"] },
    { id: "filial", title: "FILIAL", sourceEntityId: "filiais", field: "FILIAIS.FILIAL", aliases: ["FILIAL"] },
  ],
  kpis: [
    {
      id: "total-desembolsos-efetuados",
      title: "TOTAL DESEMBOLSOS EFETUADOS",
      sourceEntityId: "lancamentos",
      operation: "sum",
      aliases: ["EFETUADO"],
      valueAliases: ["EFETUADO"],
      measure: "MEDIDAS.LANÇAMENTOS",
      measures: ["MEDIDAS.LANÇAMENTOS", "MEDIDAS.VALOR TOTAL"],
      format: "currency",
    },
    {
      id: "total-viagens-em-campo",
      title: "TOTAL VIAGENS EM CAMPO",
      sourceEntityId: "lancamentos",
      operation: "min",
      aliases: ["PRODUTO"],
      valueAliases: ["PRODUTO"],
      measure: "Min(LANÇAMENTOS.PRODUTO)",
      format: "text",
    },
  ],
  charts: [
    {
      id: "desembolsos-por-periodo",
      title: "lineChart",
      type: "lineChart",
      sourceEntityId: "lancamentos",
      dimensions: [
        "LANÇAMENTOS.DATA PGTO EFETUADO.Variation.Hierarquia de datas.Ano",
        "LANÇAMENTOS.DATA PGTO EFETUADO.Variation.Hierarquia de datas.Mês",
      ],
      measures: ["Sum(LANÇAMENTOS.EFETUADO)"],
      dimensionAliases: ["DATA PGTO EFETUADO"],
      operation: "sum",
      valueAliases: ["EFETUADO"],
      interaction: "cross-filter",
      crossFilters: crossFilters([
        "principais-lancamentos", "custos-por-fornecedor", "custo-por-filial",
        "percentual-tipo-despesa", "custo-por-etapa", "principais-materiais",
      ], ["total-desembolsos-efetuados", "custo-acumulado", "custos-mensais-por-fornecedor"]),
    },
    {
      id: "principais-lancamentos",
      title: "PRINCIPAIS LANÇAMENTOS",
      type: "barChart",
      sourceEntityId: "lancamentos",
      dimensions: ["LANÇAMENTOS.FAMÍLIA", "LANÇAMENTOS.GRUPO", "LANÇAMENTOS.PRODUTO", "LANÇAMENTOS.SUBFAMÍLIA"],
      measures: ["MEDIDAS.LANÇAMENTOS", "MEDIDAS.PENDENTE PGTO"],
      dimensionAliases: ["FAMÍLIA", "GRUPO", "PRODUTO", "SUBFAMÍLIA"],
      operation: "sum",
      valueAliases: ["EFETUADO", "EMPENHADO", "LIQUIDAÇÃO"],
      interaction: "cross-filter",
      crossFilters: crossFilters([
        "custos-por-fornecedor", "desembolsos-por-periodo", "custo-por-filial",
        "empenhado-liquidacao-por-fornecedor", "percentual-tipo-despesa",
        "custo-por-etapa", "principais-materiais",
      ], ["custos-mensais-por-fornecedor"]),
    },
    {
      id: "empenhado-liquidacao-por-fornecedor",
      title: "pivotTable",
      type: "pivotTable",
      sourceEntityId: "lancamentos",
      dimensions: ["LANÇAMENTOS.FORNECEDOR", "LANÇAMENTOS.PRODUTO"],
      measures: ["Sum(LANÇAMENTOS.EMPENHADO)", "Sum(LANÇAMENTOS.LIQUIDAÇÃO)", "MEDIDAS.PENDENTE PGTO"],
      dimensionAliases: ["FORNECEDOR", "PRODUTO"],
      operation: "sum",
      valueAliases: ["EMPENHADO", "LIQUIDAÇÃO"],
      interaction: "cross-filter",
      crossFilters: crossFilters([
        "custos-por-fornecedor", "principais-lancamentos", "custo-por-filial",
        "percentual-tipo-despesa", "custo-por-etapa", "principais-materiais",
      ], ["total-desembolsos-efetuados", "desembolsos-por-periodo", "custos-mensais-por-fornecedor"]),
    },
    {
      id: "custos-mensais-por-fornecedor",
      title: "pivotTable",
      type: "pivotTable",
      sourceEntityId: "lancamentos",
      dimensions: [
        "LANÇAMENTOS.ETAPA", "LANÇAMENTOS.FORNECEDOR",
        "dCalendário.Date.Variation.Hierarquia de datas.Ano",
        "dCalendário.Date.Variation.Hierarquia de datas.Mês",
      ],
      measures: ["Sum(LANÇAMENTOS.EFETUADO)", "MEDIDAS.PENDENTE PGTO", "MEDIDAS.TOTAL P/ CASA", "MEDIDAS.VALOR TOTAL"],
      dimensionAliases: ["ETAPA", "FORNECEDOR", "DATA PGTO EFETUADO"],
      operation: "sum",
      valueAliases: ["EFETUADO", "EMPENHADO", "LIQUIDAÇÃO", "VALOR TOTAL"],
      interaction: "cross-filter",
      crossFilters: crossFilters([
        "custos-por-fornecedor", "principais-lancamentos", "custo-por-filial",
        "percentual-tipo-despesa", "custo-por-etapa", "principais-materiais",
      ], ["total-desembolsos-efetuados", "desembolsos-por-periodo", "empenhado-liquidacao-por-fornecedor"]),
    },
    {
      id: "custos-por-fornecedor",
      title: "barChart",
      type: "barChart",
      sourceEntityId: "lancamentos",
      dimensions: ["LANÇAMENTOS.FORNECEDOR"],
      measures: ["MEDIDAS.LANÇAMENTOS", "MEDIDAS.PENDENTE PGTO"],
      dimensionAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["EFETUADO", "EMPENHADO", "LIQUIDAÇÃO"],
      interaction: "cross-filter",
      crossFilters: crossFilters([
        "principais-lancamentos", "desembolsos-por-periodo", "empenhado-liquidacao-por-fornecedor",
        "custo-por-filial", "custos-mensais-por-fornecedor", "percentual-tipo-despesa",
        "custo-por-etapa", "principais-materiais",
      ], ["custo-acumulado", "total-desembolsos-efetuados"]),
    },
    {
      id: "participacao-por-etapa",
      title: "waterfallChart",
      type: "waterfallChart",
      sourceEntityId: "lancamentos",
      dimensions: ["LANÇAMENTOS.ETAPA"],
      measures: ["MEDIDAS.LANÇAMENTOS", "Divide(MEDIDAS.LANÇAMENTOS, ScopedEval(MEDIDAS.LANÇAMENTOS, []))"],
      dimensionAliases: ["ETAPA"],
      operation: "sum",
      valueAliases: ["EFETUADO"],
      interaction: "cross-filter",
      crossFilters: crossFilters([
        "total-desembolsos-efetuados", "desembolsos-por-periodo", "custos-por-fornecedor",
        "principais-lancamentos", "custo-por-filial", "custo-por-etapa",
        "percentual-tipo-despesa", "principais-materiais",
      ], ["empenhado-liquidacao-por-fornecedor"]),
    },
    {
      id: "custo-acumulado",
      title: "lineChart",
      type: "lineChart",
      sourceEntityId: "lancamentos",
      dimensions: ["ACUMULADO.Início do Mês", "ACUMULADO.TIPO"],
      measures: ["MEDIDAS.ACUMULADO CUSTO"],
      dimensionAliases: ["DATA", "DATA PGTO EFETUADO", "TIPO"],
      operation: "sum",
      valueAliases: ["QTD", "VALOR UNITÁRIO", "FRETE", "EFETUADO"],
      interaction: "cross-filter",
      crossFilters: crossFilters(),
    },
    {
      id: "custo-por-filial",
      title: "CUSTO / FILIAL",
      type: "columnChart",
      sourceEntityId: "lancamentos",
      dimensions: ["FILIAIS.FILIAL"],
      measures: ["Sum(LANÇAMENTOS.EFETUADO)", "Sum(LANÇAMENTOS.LIQUIDAÇÃO)", "Sum(LANÇAMENTOS.EMPENHADO)"],
      dimensionAliases: ["FILIAL"],
      operation: "sum",
      valueAliases: ["EFETUADO", "LIQUIDAÇÃO", "EMPENHADO"],
      interaction: "cross-filter",
      crossFilters: crossFilters(["principais-lancamentos", "custos-por-fornecedor", "custo-por-etapa", "percentual-tipo-despesa", "principais-materiais"]),
    },
    {
      id: "custo-por-etapa",
      title: "CUSTO/ETAPA",
      type: "barChart",
      sourceEntityId: "lancamentos",
      dimensions: ["LANÇAMENTOS.ETAPA"],
      measures: ["MEDIDAS.LANÇAMENTOS"],
      dimensionAliases: ["ETAPA"],
      operation: "sum",
      valueAliases: ["EFETUADO"],
      interaction: "cross-filter",
      crossFilters: crossFilters(["custo-por-filial", "principais-lancamentos", "custos-por-fornecedor", "percentual-tipo-despesa", "principais-materiais"]),
    },
    {
      id: "percentual-tipo-despesa",
      title: "% TIPO DESPESA",
      type: "columnChart",
      sourceEntityId: "produtos",
      dimensions: ["CADASTROPRODUTO.TIPODESPESA", "FILIAIS.FILIAL"],
      measures: ["MEDIDAS.LANÇAMENTOS"],
      dimensionAliases: ["TIPODESPESA", "TIPO DESPESA", "FILIAL"],
      operation: "sum",
      valueAliases: ["EFETUADO"],
      interaction: "cross-filter",
      crossFilters: crossFilters(["custo-por-filial", "total-viagens-em-campo", "principais-lancamentos", "custo-por-etapa", "custos-por-fornecedor", "principais-materiais"]),
    },
    {
      id: "principais-materiais",
      title: "PRINCIPAIS MATERIAIS",
      type: "barChart",
      sourceEntityId: "lancamentos",
      dimensions: ["LANÇAMENTOS.FAMÍLIA", "LANÇAMENTOS.GRUPO", "LANÇAMENTOS.PRODUTO", "LANÇAMENTOS.SUBFAMÍLIA"],
      measures: ["MEDIDAS.LANÇAMENTOS", "MEDIDAS.PENDENTE PGTO"],
      dimensionAliases: ["FAMÍLIA", "GRUPO", "PRODUTO", "SUBFAMÍLIA"],
      operation: "sum",
      valueAliases: ["EFETUADO", "EMPENHADO", "LIQUIDAÇÃO"],
      interaction: "cross-filter",
      crossFilters: crossFilters(["custo-por-filial", "total-viagens-em-campo", "custo-por-etapa", "percentual-tipo-despesa", "principais-lancamentos", "custos-por-fornecedor"]),
    },
  ],
  table: {
    id: "lancamentos-detalhados",
    title: "tableEx",
    type: "tableEx",
    sourceEntityId: "lancamentos",
    source: "LANÇAMENTOS",
    columns: [
      { id: "data", title: "DATA", field: "LANÇAMENTOS.DATA", aliases: ["DATA"], type: "date" },
      { id: "data-pagamento", title: "DATA PGTO EFETUADO", field: "LANÇAMENTOS.DATA PGTO EFETUADO", aliases: ["DATA PGTO EFETUADO"], type: "date" },
      { id: "efetuado", title: "EFETUADO", field: "LANÇAMENTOS.EFETUADO", aliases: ["EFETUADO"], type: "currency" },
      { id: "filial", title: "FILIAL", field: "LANÇAMENTOS.FILIAL", aliases: ["FILIAL"] },
      { id: "fornecedor", title: "FORNECEDOR", field: "LANÇAMENTOS.FORNECEDOR", aliases: ["FORNECEDOR"] },
      { id: "frete", title: "FRETE", field: "LANÇAMENTOS.FRETE", aliases: ["FRETE"], type: "currency" },
      { id: "id", title: "ID", field: "LANÇAMENTOS.ID", aliases: ["ID", "Id"] },
      { id: "produto", title: "PRODUTO", field: "LANÇAMENTOS.PRODUTO", aliases: ["PRODUTO"] },
      { id: "quantidade", title: "QTD", field: "LANÇAMENTOS.QTD", aliases: ["QTD"], type: "number" },
      { id: "total", title: "TOTAL", field: "LANÇAMENTOS.TOTAL", aliases: ["TOTAL"], type: "currency" },
      { id: "valor-unitario", title: "VALOR UNITÁRIO", field: "LANÇAMENTOS.VALOR UNITÁRIO", aliases: ["VALOR UNITÁRIO", "VALORUNITARIO"], type: "currency" },
    ],
    crossFilters: crossFilters([
      "principais-lancamentos", "custos-por-fornecedor", "custo-por-filial",
      "custo-por-etapa", "percentual-tipo-despesa", "principais-materiais",
    ], ["desembolsos-por-periodo", "total-desembolsos-efetuados", "empenhado-liquidacao-por-fornecedor"]),
  },
});

export default FINANCEIRO_DEFINITION;
