function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const RH_FILTER_TARGETS = {
  "custo-por-data": ["custo-fornecedor", "mao-de-obra-etapa", "custo-profissao", "valores-pendentes-pagamento", "distribuicao-forma-pagamento", "mao-de-obra-filial", "presencas-profissional", "profissoes-dia", "profissionais-etapa", "tipo-despesa"],
  "mao-de-obra-etapa": ["valores-pendentes-pagamento", "custo-profissao", "custo-fornecedor", "tipo-despesa", "profissoes-dia", "mao-de-obra-filial", "distribuicao-forma-pagamento", "presencas-profissional", "profissionais-etapa"],
  "custo-fornecedor": ["mao-de-obra-etapa", "custo-profissao", "valores-pendentes-pagamento", "distribuicao-forma-pagamento", "tipo-despesa", "profissoes-dia", "presencas-profissional", "mao-de-obra-filial", "profissionais-etapa"],
  "custo-profissao": ["mao-de-obra-etapa", "custo-fornecedor", "distribuicao-forma-pagamento", "valores-pendentes-pagamento", "tipo-despesa", "profissoes-dia", "mao-de-obra-filial", "presencas-profissional", "profissionais-etapa"],
  "profissoes-dia": ["valores-pendentes-pagamento", "mao-de-obra-etapa", "custo-profissao", "custo-fornecedor", "tipo-despesa", "mao-de-obra-filial", "distribuicao-forma-pagamento", "presencas-profissional", "profissionais-etapa"],
  "valores-pendentes-pagamento": ["custo-profissao", "mao-de-obra-etapa", "custo-fornecedor", "distribuicao-forma-pagamento", "profissionais-etapa", "profissoes-dia", "presencas-profissional"],
  "distribuicao-forma-pagamento": ["mao-de-obra-etapa", "custo-profissao", "valores-pendentes-pagamento", "custo-fornecedor", "profissoes-dia", "tipo-despesa", "mao-de-obra-filial", "presencas-profissional", "profissionais-etapa"],
  "tipo-despesa": ["custo-profissao", "mao-de-obra-etapa", "custo-fornecedor", "valores-pendentes-pagamento", "profissoes-dia", "distribuicao-forma-pagamento", "mao-de-obra-filial", "presencas-profissional", "profissionais-etapa"],
  "mao-de-obra-filial": ["custo-fornecedor", "total-mao-de-obra", "custo-profissao", "mao-de-obra-etapa", "tipo-despesa", "valores-pendentes-pagamento", "distribuicao-forma-pagamento", "lancamentos", "presencas-profissional", "profissoes-dia", "profissionais-etapa"],
  "presencas-profissional": ["mao-de-obra-filial", "mao-de-obra-etapa", "profissoes-dia", "custo-profissao", "custo-fornecedor", "tipo-despesa", "valores-pendentes-pagamento", "distribuicao-forma-pagamento", "profissionais-etapa"],
  "profissionais-etapa": ["custo-profissao", "mao-de-obra-etapa", "custo-fornecedor", "tipo-despesa", "valores-pendentes-pagamento", "profissoes-dia", "distribuicao-forma-pagamento", "mao-de-obra-filial", "presencas-profissional"],
};
const crossFiltersFor = id => ({ filter: RH_FILTER_TARGETS[id] || [], highlight: [], none: [] });

export const RECURSOS_HUMANOS_DEFINITION = deepFreeze({
  id: "recursos-humanos",
  title: "RECURSOS HUMANOS",
  sourceEntityIds: [
    "produtos",
    "descricoes-de-presenca",
    "filiais",
    "fornecedores",
    "lancamentos-de-obras",
    "lancamentos",
  ],
  filters: [
    {
      id: "presenca-presente",
      title: "PRESENÇA",
      sourceEntityId: "descricoes-de-presenca",
      aliases: ["PRESENCA"],
      scope: "global",
      operator: "in",
      values: ["PRESENTE"],
    },
    { id: "status-fornecedor", title: "STATUS", sourceEntityId: "fornecedores", aliases: ["STATUS"] },
    { id: "fornecedor", title: "FORNECEDOR", sourceEntityId: "descricoes-de-presenca", aliases: ["FORNECEDOR"] },
    { id: "produto", title: "PRODUTO", sourceEntityId: "lancamentos", aliases: ["PRODUTO"] },
    { id: "profissao", title: "PROFISSÃO", sourceEntityId: "fornecedores", aliases: ["PROFISSAO"] },
    { id: "etapa", title: "ETAPA", sourceEntityId: "lancamentos", aliases: ["ETAPA"] },
    { id: "filial", title: "FILIAL", sourceEntityId: "filiais", aliases: ["FILIAL"] },
    { id: "mes", title: "DATA", sourceEntityId: "lancamentos", aliases: ["DATA PGTO EFETUADO", "Date"], granularity: "month" },
    { id: "ano", title: "ANO", sourceEntityId: "lancamentos", aliases: ["DATA PGTO EFETUADO", "Date"], granularity: "year" },
    { id: "forma-pagamento", title: "FORMA PGTO", sourceEntityId: "lancamentos", aliases: ["CONTA"] },
    { id: "imovel", title: "IMÓVEL", sourceEntityId: "descricoes-de-presenca", aliases: ["IMOVEL"] },
    { id: "atividade-executada", title: "ATIVIDADE EXECUTADA", sourceEntityId: "descricoes-de-presenca", aliases: ["ATIVIDADEEXECUTADA"] },
    { id: "status-obra", title: "STATUS", sourceEntityId: "lancamentos-de-obras", aliases: ["STATUS"] },
  ],
  kpis: [
    {
      id: "total-mao-de-obra",
      title: "TOTAL MÃO DE OBRA",
      sourceEntityId: "lancamentos",
      operation: "sum",
      valueAliases: ["TOTAL"],
    },
    {
      id: "valor-pendente",
      title: "VALOR PENDENTE",
      sourceEntityId: "descricoes-de-presenca",
      operation: "sum",
      valueAliases: ["VLR DIARIO", "VLR DIÁRIO"],
    },
  ],
  charts: [
    {
      id: "custo-por-data",
      title: "lineChart",
      type: "line",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["DATA PGTO EFETUADO"],
      operation: "sum",
      valueAliases: ["TOTAL"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("custo-por-data"),
    },
    {
      id: "custo-fornecedor",
      title: "CUSTO/FORNECEDOR",
      type: "bar",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS", "PENDENTE PGTO"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("custo-fornecedor"),
    },
    {
      id: "mao-de-obra-etapa",
      title: "MÃO DE OBRA/ETAPA",
      type: "bar",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["ETAPA"],
      operation: "sum",
      valueAliases: ["TOTAL"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("mao-de-obra-etapa"),
    },
    {
      id: "valores-pendentes-pagamento",
      title: "VALORES PENDENTES PGTO",
      type: "bar",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["VLR DIÁRIO", "VLR DIARIO"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("valores-pendentes-pagamento"),
    },
    {
      id: "custo-profissao",
      title: "CUSTO/PROFISSÃO",
      type: "bar",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["PROFISSAO"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("custo-profissao"),
    },
    {
      id: "profissoes-dia",
      title: "PROFISSÕES/DIA",
      type: "column",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["Date"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("profissoes-dia"),
    },
    {
      id: "distribuicao-forma-pagamento",
      title: "DISTRIBUIÇÃO POR FORMA PGTO",
      type: "column",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["Date"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("distribuicao-forma-pagamento"),
    },
    {
      id: "tipo-despesa",
      title: "% TIPO DESPESA",
      type: "hundred-percent-stacked-column",
      sourceEntityId: "produtos",
      dimensionAliases: ["TIPODESPESA"],
      seriesAliases: ["FILIAL"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("tipo-despesa"),
    },
    {
      id: "mao-de-obra-filial",
      title: "MÃO DE OBRA/FILIAL",
      type: "column",
      sourceEntityId: "lancamentos",
      dimensionAliases: ["FILIAL"],
      seriesAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["EFETUADO", "EMPENHADO"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("mao-de-obra-filial"),
    },
    {
      id: "presencas-profissional",
      title: "PRESENÇAS/PROFISSIONAL",
      type: "bar",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["FORNECEDOR"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("presencas-profissional"),
    },
    {
      id: "profissionais-etapa",
      title: "barChart",
      type: "bar",
      sourceEntityId: "descricoes-de-presenca",
      dimensionAliases: ["ETAPA"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
      crossFilters: crossFiltersFor("profissionais-etapa"),
    },
  ],
  table: {
    id: "detalhes-rh",
    title: "tableEx",
    viewsOnly: true,
    columns: [
      { id: "data-pagamento", title: "DATA PGTO EFETUADO", aliases: ["DATA PGTO EFETUADO"], type: "date" },
      { id: "data-presenca", title: "DataFormatada", aliases: ["DataFormatada"] },
      { id: "filial", title: "FILIAL", aliases: ["FILIAL"] },
      { id: "fornecedor", title: "FORNECEDOR", aliases: ["FORNECEDOR"] },
      { id: "id", title: "ID", aliases: ["ID", "Id"] },
      { id: "total", title: "TOTAL", aliases: ["TOTAL"], type: "currency" },
      { id: "valor-diario", title: "VLR DIÁRIO", aliases: ["VLR DIÁRIO", "VLR DIARIO"], type: "currency" },
    ],
    views: [
      {
        id: "lancamentos",
        title: "tableEx",
        sourceEntityId: "lancamentos",
        columnIds: ["data-pagamento", "filial", "fornecedor", "id", "total"],
        interaction: "cross-filter",
        crossFilters: {
          filter: ["mao-de-obra-etapa", "custo-fornecedor", "custo-profissao", "profissionais-etapa"],
          highlight: ["profissoes-dia", "presencas-profissional"],
          none: [],
        },
      },
      {
        id: "presencas",
        title: "tableEx",
        sourceEntityId: "descricoes-de-presenca",
        columnIds: ["data-presenca", "fornecedor", "id", "valor-diario"],
        interaction: "cross-filter",
        crossFilters: { filter: [], highlight: [], none: [] },
      },
    ],
  },
});

export default RECURSOS_HUMANOS_DEFINITION;
