function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

export const RECURSOS_HUMANOS_DEFINITION = deepFreeze({
  id: "recursos-humanos",
  title: "RECURSOS HUMANOS",
  sourceEntityIds: [
    "produtos",
    "descricoes-de-presenca",
    "filiais",
    "fornecedores",
    "lancamentos-de-obras",
    "lancamentos",
  ],
  filters: [
    {
      id: "presenca-presente",
      title: "PRESENÇA",
      aliases: ["PRESENCA"],
      scope: "global",
      operator: "in",
      values: ["PRESENTE"],
    },
    { id: "status-fornecedor", title: "STATUS", aliases: ["STATUS"] },
    { id: "fornecedor", title: "FORNECEDOR", aliases: ["FORNECEDOR"] },
    { id: "produto", title: "PRODUTO", aliases: ["PRODUTO"] },
    { id: "profissao", title: "PROFISSÃO", aliases: ["PROFISSAO"] },
    { id: "etapa", title: "ETAPA", aliases: ["ETAPA"] },
    { id: "filial", title: "FILIAL", aliases: ["FILIAL"] },
    { id: "mes", title: "DATA", aliases: ["Date"], granularity: "month" },
    { id: "ano", title: "ANO", aliases: ["Date"], granularity: "year" },
    { id: "forma-pagamento", title: "FORMA PGTO", aliases: ["CONTA"] },
    { id: "imovel", title: "IMÓVEL", aliases: ["IMOVEL"] },
    { id: "atividade-executada", title: "ATIVIDADE EXECUTADA", aliases: ["ATIVIDADEEXECUTADA"] },
    { id: "status-obra", title: "STATUS", aliases: ["STATUS"] },
  ],
  kpis: [
    {
      id: "total-mao-de-obra",
      title: "TOTAL MÃO DE OBRA",
      operation: "sum",
      valueAliases: ["TOTAL"],
    },
    {
      id: "valor-pendente",
      title: "VALOR PENDENTE",
      operation: "sum",
      valueAliases: ["VLR DIARIO", "VLR DIÁRIO"],
    },
  ],
  charts: [
    {
      id: "custo-por-data",
      title: "lineChart",
      type: "line",
      dimensionAliases: ["DATA PGTO EFETUADO"],
      operation: "sum",
      valueAliases: ["TOTAL"],
      interaction: "cross-filter",
    },
    {
      id: "custo-fornecedor",
      title: "CUSTO/FORNECEDOR",
      type: "bar",
      dimensionAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS", "PENDENTE PGTO"],
      interaction: "cross-filter",
    },
    {
      id: "mao-de-obra-etapa",
      title: "MÃO DE OBRA/ETAPA",
      type: "bar",
      dimensionAliases: ["ETAPA"],
      operation: "sum",
      valueAliases: ["TOTAL"],
      interaction: "cross-filter",
    },
    {
      id: "valores-pendentes-pagamento",
      title: "VALORES PENDENTES PGTO",
      type: "bar",
      dimensionAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["VLR DIÁRIO", "VLR DIARIO"],
      interaction: "cross-filter",
    },
    {
      id: "custo-profissao",
      title: "CUSTO/PROFISSÃO",
      type: "bar",
      dimensionAliases: ["PROFISSAO"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
    },
    {
      id: "profissoes-dia",
      title: "PROFISSÕES/DIA",
      type: "column",
      dimensionAliases: ["Date"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "distribuicao-forma-pagamento",
      title: "DISTRIBUIÇÃO POR FORMA PGTO",
      type: "column",
      dimensionAliases: ["Date"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "tipo-despesa",
      title: "% TIPO DESPESA",
      type: "hundred-percent-stacked-column",
      dimensionAliases: ["TIPODESPESA"],
      seriesAliases: ["FILIAL"],
      operation: "sum",
      valueAliases: ["LANÇAMENTOS"],
      interaction: "cross-filter",
    },
    {
      id: "mao-de-obra-filial",
      title: "MÃO DE OBRA/FILIAL",
      type: "column",
      dimensionAliases: ["FILIAL"],
      seriesAliases: ["FORNECEDOR"],
      operation: "sum",
      valueAliases: ["EFETUADO", "EMPENHADO"],
      interaction: "cross-filter",
    },
    {
      id: "presencas-profissional",
      title: "PRESENÇAS/PROFISSIONAL",
      type: "bar",
      dimensionAliases: ["FORNECEDOR"],
      seriesAliases: ["FORMAPGTO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
    {
      id: "profissionais-etapa",
      title: "barChart",
      type: "bar",
      dimensionAliases: ["ETAPA"],
      seriesAliases: ["PROFISSAO"],
      operation: "count",
      valueAliases: ["FORNECEDOR"],
      interaction: "cross-filter",
    },
  ],
  table: {
    id: "detalhes-rh",
    title: "tableEx",
    columns: [
      { id: "data-pagamento", title: "DATA PGTO EFETUADO", aliases: ["DATA PGTO EFETUADO"], type: "date" },
      { id: "data-presenca", title: "DataFormatada", aliases: ["DataFormatada"] },
      { id: "filial", title: "FILIAL", aliases: ["FILIAL"] },
      { id: "fornecedor", title: "FORNECEDOR", aliases: ["FORNECEDOR"] },
      { id: "id", title: "ID", aliases: ["ID", "Id"] },
      { id: "total", title: "TOTAL", aliases: ["TOTAL"], type: "currency" },
      { id: "valor-diario", title: "VLR DIÁRIO", aliases: ["VLR DIÁRIO", "VLR DIARIO"], type: "currency" },
    ],
    views: [
      {
        id: "lancamentos",
        title: "tableEx",
        columnIds: ["data-pagamento", "filial", "fornecedor", "id", "total"],
        interaction: "cross-filter",
      },
      {
        id: "presencas",
        title: "tableEx",
        columnIds: ["data-presenca", "fornecedor", "id", "valor-diario"],
        interaction: "cross-filter",
      },
    ],
  },
});

export default RECURSOS_HUMANOS_DEFINITION;
